#!/usr/bin/python

import os

def print_results(name, exresult, extime, result, time, failed):
    print "-----------------------------------------------"
    print "*** Running '%s' test... ***" % name
    print "-----------------------------------------------"

    print "Python Result  : %s" % exresult
    print "PyStoch Result : %s" % result
    print
    print "Python Time    : %s seconds" % extime
    print "PyStoch Time   : %s seconds" % time
    print

    if failed:
        print "FAILED"
    else:
        print "PASSED"

tests = []
passed = []
failed = []

for f in os.listdir('.'):
    if os.path.isdir(f):
        files =  os.listdir(f)
        if 'test' in files:
            os.chdir(f)
            execfile('test')


print "-----------------------------------------------"
print
print "Tests passed: %s/%s" % (len(passed), len(tests))
print "Tests failed: %s/%s" % (len(failed), len(tests))
print
print "Failed tests: %s" % ", ".join(failed)
